// Generates ai/components.md from the kit source: every exported component, its
// doc comment, its props (name, type, doc) and the routes that use it.
// Run after adding or changing components:  npm run catalog
import { readFileSync, readdirSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const KIT = join(ROOT, "src/components/nova");
const APP = join(ROOT, "src/app");

const walk = (dir) =>
  readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });

const pages = walk(APP).filter((f) => f.endsWith("page.tsx") || f.endsWith("not-found.tsx"));
const routeOf = (f) => {
  const r = "/" + relative(APP, f).replace(/(^|\/)(page|not-found)\.tsx$/, "");
  return f.endsWith("not-found.tsx") ? "404" : r === "/" ? "/" : r.replace(/\/$/, "");
};
const pageSrc = pages.map((f) => ({ route: routeOf(f), src: readFileSync(f, "utf8") }));

const index = readFileSync(join(KIT, "index.ts"), "utf8");
const sections = [];
let current = "Core";
for (const line of index.split("\n")) {
  const g = line.match(/^\/\/ (.+)/);
  if (g) current = g[1];
  const m = line.match(/from "\.\/([\w-]+)"/);
  if (m && !sections.find((s) => s.file === m[1])) sections.push({ file: m[1], group: current });
}

// Doc comment immediately above `export function Name`.
const docAbove = (src, idx) => {
  const before = src.slice(0, idx).trimEnd();
  if (!before.endsWith("*/")) return "";
  const start = before.lastIndexOf("/**");
  return before
    .slice(start + 3, -2)
    .split("\n")
    .map((l) => l.replace(/^\s*\* ?/, "").trim())
    .filter(Boolean)
    .join(" ");
};

// Props from `export type XProps = { ... }` (top-level keys only).
const propsOf = (src, name) => {
  const m = src.match(new RegExp(`export type ${name}Props\\s*=\\s*(?:[^{]*&\\s*)?{`));
  if (!m) return [];
  let i = m.index + m[0].length, depth = 1, body = "";
  while (i < src.length && depth) {
    const c = src[i++];
    if (c === "{") depth++;
    if (c === "}") depth--;
    if (depth) body += c;
  }
  const out = [];
  let doc = "";
  let d = 0;
  for (const raw of body.split("\n")) {
    const line = raw.trim();
    if (d === 0) {
      const dm = line.match(/^\/\*\*\s*(.*?)\s*\*\/$/) || line.match(/^\/\*\*\s*(.*)$/) || line.match(/^\*\s*(.*?)(\*\/)?$/);
      if (line.startsWith("/**") || (line.startsWith("*") && !line.startsWith("*/"))) {
        doc += " " + (dm ? dm[1].replace(/\*\/$/, "") : "");
        continue;
      }
      const pm = line.match(/^(\w+)(\?)?:\s*(.+?);?$/);
      if (pm) {
        let type = pm[3].replace(/;$/, "");
        // Expand a local union alias (`type Size = "lg" | "card"`) so the allowed values show.
        const alias = type.match(/^(\w+)$/) && src.match(new RegExp(`^type ${type}\\s*=\\s*([^;{]+);`, "m"));
        if (alias) type = alias[1].replace(/\s+/g, " ").trim();
        out.push({ name: pm[1], optional: !!pm[2], type, doc: doc.trim() });
        doc = "";
      }
    }
    d += (raw.match(/[{(]/g) || []).length - (raw.match(/[})]/g) || []).length;
    if (d < 0) d = 0;
  }
  return out;
};

let md = `# NOVA component catalog\n\nGenerated by \`npm run catalog\` from \`src/components/nova\`. Import everything from\n\`@/components/nova\`. Every component renders with zero props (built-in defaults) unless a prop is\nmarked required. Rules for using and extending them: \`ai/design-system.md\`.\n`;

let group = "";
for (const { file, group: g } of sections) {
  const src = readFileSync(join(KIT, file + ".tsx"), "utf8");
  if (g !== group) {
    group = g;
    md += `\n## ${group}\n`;
  }
  for (const m of src.matchAll(/^export function (\w+)/gm)) {
    const name = m[1];
    if (!/^[A-Z]/.test(name)) continue;
    const doc = docAbove(src, m.index);
    const used = pageSrc.filter((p) => new RegExp(`<${name}[\\s/>]`).test(p.src)).map((p) => p.route);
    md += `\n### \`<${name} />\` · \`src/components/nova/${file}.tsx\`\n`;
    if (doc) md += `\n${doc}\n`;
    if (used.length) md += `\nUsed on: ${used.map((r) => `\`${r}\``).join(", ")}\n`;
    const props = propsOf(src, name);
    if (props.length) {
      md += `\n| Prop | Type | Notes |\n| --- | --- | --- |\n`;
      for (const p of props)
        md += `| \`${p.name}\`${p.optional ? "" : " (required)"} | \`${p.type.replace(/\|/g, "\\|")}\` | ${p.doc.replace(/\|/g, "\\|")} |\n`;
    }
  }
}

md += `\n## Pages\n\n| Route | File | Sections |\n| --- | --- | --- |\n`;
for (const p of pageSrc.sort((a, b) => a.route.localeCompare(b.route))) {
  const used = [...new Set([...p.src.matchAll(/<([A-Z]\w+)[\s/>]/g)].map((m) => m[1]))].filter((n) => n !== "Metadata");
  const file = relative(ROOT, pages.find((f) => routeOf(f) === p.route));
  md += `| \`${p.route}\` | \`${file}\` | ${used.join(", ")} |\n`;
}

writeFileSync(join(ROOT, "ai/components.md"), md);
console.log(`ai/components.md: ${sections.length} files, ${pageSrc.length} pages`);
